# Generated by Django 4.0.3 on 2022-08-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('n_de_pie', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('list_tiempo', models.CharField(max_length=20000)),
                ('list_pie_e_x', models.CharField(max_length=20000)),
                ('list_pie_e_y', models.CharField(max_length=20000)),
                ('list_pression_e', models.CharField(max_length=20000)),
                ('list_pie_d_x', models.CharField(max_length=20000)),
                ('list_pie_d_y', models.CharField(max_length=20000)),
                ('list_pression_d', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/')),
            ],
        ),
    ]
